### ISSUE TITLE
biopython import error

### ISSUE THREAD

**Issue by nick-youngblut** [victoriapascal/gutsmash_doc#1]
I'm posting this here, since the [gutSMASH](https://github.com/victoriapascal/gutsmash/tree/gutsmash) does not allow for issue posting. 

It appears that your fork of antismash is suffering from the same biopython problem that plagued antismash (https://github.com/antismash/antismash/issues/293):

```
$ ./run_gutsmash.py -h
Traceback (most recent call last):
  File "./run_gutsmash.py", line 6, in <module>
    from antismash.__main__ import entrypoint
  File "/ebio/abt3_projects/software/dev/tmp/gutsmash/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/ebio/abt3_projects/software/dev/tmp/gutsmash/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/ebio/abt3_projects/software/dev/tmp/gutsmash/antismash/common/record_processing.py", line 20, in <module>
    from antismash.common.secmet import Record
  File "/ebio/abt3_projects/software/dev/tmp/gutsmash/antismash/common/secmet/__init__.py", line 11, in <module>
    from .record import Record
  File "/ebio/abt3_projects/software/dev/tmp/gutsmash/antismash/common/secmet/record.py", line 20, in <module>
    from Bio import Alphabet, SeqIO
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/gutsmash/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

Noting this issue in the gutSMASH docs would be helpful.

**Comment by nick-youngblut** [comment]
A conda env setup that should work:

```
mamba create -n gutsmash python=3 hmmer fasttree diamond=0.8.36 muscle prodigal blast biopython=1.76 helperlibs bcbio-gff pysvg-py3 scikit-learn matplotlib jinja2 pyscss
```

It's basically the same as the [antismash recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/antismash/meta.yaml), which is expected, given the code overlap. That should make it relatively easy to create a bioconda recipe for gutSMASH 😁

**Comment by stefcamp** [comment]
I had the same problem and I solved it by installing biopython=1.76; this is because starting from biopython=1.78 "alphabet" was removed. Now I have another issue that I cannot solve.
Does anyone have a ".yaml" file of the environment with the proper configuration?
Thanks

**Comment by stefcamp** [comment]
Sorry for writing here comments but when I run:
python3 run_gutsmash.py --genefinding-tool prodigal --cb-knownclusters --enable-genefunctions ./test/Clostridium_difficile.fna --output-dir ./test_out/

I have an error (while it is not present if I remove the option --enable-genefunctions); and also I have another error when I add the option --fullhmmer)

/home/bioinfo/anaconda3/envs/antismash5.1.2-4/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
Traceback (most recent call last):
  File "run_gutsmash.py", line 9, in <module>
    entrypoint()
  File "/home/bioinfo/bin/gutsmash/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/bioinfo/bin/gutsmash/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/bioinfo/bin/gutsmash/antismash/main.py", line 609, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/bioinfo/bin/gutsmash/antismash/main.py", line 688, in _run_antismash
    write_outputs(results, options)
  File "/home/bioinfo/bin/gutsmash/antismash/main.py", line 408, in write_outputs
    html.write(results.records, module_results_per_record, options)
  File "/home/bioinfo/bin/gutsmash/antismash/outputs/html/__init__.py", line 98, in write
    generate_webpage(records, results, options)
  File "/home/bioinfo/bin/gutsmash/antismash/outputs/html/generator.py", line 140, in generate_webpage
    html_sections = generate_html_sections(record_layers_with_regions, results_by_record_id, options)
  File "/home/bioinfo/bin/gutsmash/antismash/outputs/html/generator.py", line 103, in generate_html_sections
    sections.append(handler.generate_html(region, handler_results, record, options))
  File "/home/bioinfo/bin/gutsmash/antismash/modules/clusterblast/html_output.py", line 43, in generate_html
    div = generate_div(region_layer, record_layer, options_layer, "knownclusterblast", tooltip)
UnboundLocalError: local variable 'tooltip' referenced before assignment

**Comment by victoriapascal** [comment]
Hi Stefano, with the last commit I made the problem of the tooltip should have been solved. Let me know if it does not work for you. Also, you can check the conda environment I use to run gutSMASH by downloading the yml file from here: https://drive.google.com/file/d/1NqtQgPU8XDOYfXSlGiKx9VMd7VMRjqZR/view?usp=sharing. Regarding your error with the --fullhmmer option, I could not reproduce your error. Does it happen with any input file you use?

**Comment by stefcamp** [comment]
Dear Victoria,
thanks for sharing the "yml" file, I tried to use it, but conda was not able to solve the environment due to the conflicts between packages. However, by checking the "yml" file, I was able to find that the problem was due to the version of hmmer2 and I solved using "conda install -c bioconda hmmer2=2.3.2"
Thanks!
