### ISSUE TITLE
gutSMASH failing when using FASTA

### ISSUE THREAD

**Issue by raphenya** [victoriapascal/gutsmash_doc#3]
@victoriapascal gutSMASH works fine with `gbk` files downloaded from ncbi, but it fails when I use FASTA. I tested with `gbk` and `FASTA` from same ncbi accession. I get the same error, shown below, for multiple fastas I tested.

```
cat NC_007795.1.log
/home/raphenar/.local/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
Traceback (most recent call last):
  File "gutsmash/run_gutsmash.py", line 9, in <module>
    entrypoint()
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/main.py", line 609, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/main.py", line 669, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/main.py", line 184, in run_detection
    run_module(record, cast(AntismashModule, module), options, module_results, timings)
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/main.py", line 230, in run_module
    results = module.run_on_record(record, results, options)
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/detection/genefunctions/__init__.py", line 131, in run_on_record
    for result in run_tools(record, options):
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/detection/genefunctions/tools.py", line 33, in run_tools
    return [func(record.id, cds_features, options) for func in functions]
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/detection/genefunctions/tools.py", line 33, in <listcomp>
    return [func(record.id, cds_features, options) for func in functions]
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/detection/genefunctions/smcogs.py", line 30, in classify
    hits = scan_for_functions(cds_features, hmm_file, hmmscan_opts=["-E", "1E-16"])
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/detection/genefunctions/core.py", line 82, in scan_for_functions
    results = subprocessing.run_hmmscan(database, search_fasta, hmmscan_opts)
  File "/home/raphenar/msc_project/gutSMASH/gutsmash/antismash/common/subprocessing/hmmscan.py", line 42, in run_hmmscan
    raise RuntimeError('hmmscan returned %d: %r while scanning %r' % (
RuntimeError: hmmscan returned 1: 'roject/gutSMASH/gutsmash/antismash/detection/genefunctions/gut_data/smcogs.hmm: use hmmpress first' while scanning '>ctg1_157\nMTIKVGIIGCGGIANGKHMPSLQKVENVEMIAFCDVDISKAASAAEAYGTDNAKVYDDYKALLKDDTIDVIHVCTPNDSHCEITVAGLHA'
```

**Comment by victoriapascal** [comment]
Could you share the command you are using? Also, is the smcogs database in the correct path (gutsmash/antismash/detection/genefunctions/gut_data)  and hmmpressed? You can download it from here: https://gutsmash.bioinformatics.nl/download.html

**Comment by raphenya** [comment]
>Could you share the command you are using?

```
python3 gutsmash/run_gutsmash.py --genefinding-tool prodigal --cb-knownclusters --enable-genefunctions --cpus 60 NC_007795.1.fasta > NC_007795.1.log 2>&1
```

>Also, is the smcogs database in the correct path (gutsmash/antismash/detection/genefunctions/gut_data)

```
~/msc_project/gutSMASH/gutsmash/antismash/detection/genefunctions/gut_data$ tree -L 2
.
├── cog_annotations_original.txt
├── cog_annotations.txt
├── smcogs.hmm
└── smcogs_original.hmm

0 directories, 4 files
```
@victoriapascal do I run `hmmpress` on `smcogs.hmm` to generate indexes?

**Comment by raphenya** [comment]
@victoriapascal dang it! that was it. I ran the following: 
```
hmmpress smcogs.hmm 
Working...    done.
Pressed and indexed 62 HMMs (62 names).
Models pressed into binary file:   smcogs.hmm.h3m
SSI index for binary model file:   smcogs.hmm.h3i
Profiles (MSV part) pressed into:  smcogs.hmm.h3f
Profiles (remainder) pressed into: smcogs.hmm.h3p
```

and this command worked:

```
python3 gutsmash/run_gutsmash.py --genefinding-tool prodigal --cb-knownclusters --enable-genefunctions --cpus 60 NC_007795.1.fasta > NC_007795.1.log 2>&1
```

Cheers.
